/**
 * ANTLR 4 parser grammar for MC-Annotate output files.
 *
 * This grammar defines the structure of output files generated by MC-Annotate,
 * a tool for RNA 3D structure annotation. The format consists of:
 * - Residue definitions (sequence)
 * - Stacking interactions (adjacent and non-adjacent)
 * - Base-pair interactions with Leontis-Westhof nomenclature
 *
 * @author Federico Di Petta
 * @see MCAnnotateLexer
 */
parser grammar MCAnnotateParser;

options {
    tokenVocab = MCAnnotateLexer;
}

// Root rule
mcAnnotateFile
    : line* EOF
    ;

line
    : sequenceLine
    | stackingLine
    | bondLine
    | headerLine
    | summaryLine
    ;

// ------------------------------------------------
// Sequence section
// ------------------------------------------------
sequenceLine
    : residueId=RESIDUE_ID COLON nucleotide=BASE residueInfo*
    | residueId=RESIDUE_ID COLON nucleotideId=RESIDUE_ID  // e.g., A76 : A23
    | residueId=RESIDUE_ID COLON nucleotideText=TEXT residueInfo*
    ;

residueInfo
    : TEXT
    | BASE
    ;

// ------------------------------------------------
// Headers
// ------------------------------------------------
headerLine
    : ADJACENT_STACKINGS
    | NON_ADJACENT_STACKINGS
    | BASE_PAIRS
    ;

// ------------------------------------------------
// Stacking line
// ------------------------------------------------
stackingLine
    : id1=RESIDUE_ID DASH id2=RESIDUE_ID COLON stackingInfo+
    ;

stackingInfo
    : STACKING_TYPE
    | TEXT
    ;

// ------------------------------------------------
// Bond/Base-pair line
// ------------------------------------------------
bondLine
    : id1=RESIDUE_ID DASH id2=RESIDUE_ID COLON 
      base1=(BASE|TEXT) DASH base2=(BASE|TEXT) 
      edgeInteraction pairingInfo?
    ;

// Edge interaction: Ww/Ws, O2'/Hh, Ss/Ss, etc.
edgeInteraction
    : edge1=(EDGE|TEXT) SLASH edge2=(EDGE|TEXT)
    ;

pairingInfo
    : PAIRING orientation? configuration? saenger? ONE_HBOND?
    ;

orientation
    : PARALLEL
    | ANTIPARALLEL
    ;

configuration
    : CIS
    | TRANS
    ;

saenger
    : SAENGER
    | TEXT  // fallback for unusual classifications
    ;

// ------------------------------------------------
// Summary lines
// ------------------------------------------------
summaryLine
    : NUMBER_OF S_TEXT+ S_EQUALS S_NUMBER
    ;
