/*
 * ANTLR 4 lexer grammar for mc-annotate output files.
 *
 * This lexer defines the tokens used by the McAnnotateParser to parse output
 * files generated by the mc-annotate tool. The output typically contains
 * sections for residue conformations, adjacent and non-adjacent stackings,
 * and base-pair interactions. The lexer uses modes to handle each section
 * separately and to skip headers and statistical lines.
 *
 * @author Francesco Palozzi
 * @see McAnnotateParser
 */
lexer grammar MCAnnotateLexer;

// ------------------------------------------------
// Fragments
// ------------------------------------------------
fragment WS_CHAR: [ \t];
fragment NEWLINE_CHAR: '\r'? '\n';
fragment IUPAC_CODE: [ACGUacguTtRrYysSWwKkMmBbDdHhVvNn-];
fragment COLUMN: ':';


// ----------------------------------------------------------------
// Default mode - for everything except specialized modes
// ----------------------------------------------------------------
WS: WS_CHAR+ -> skip;
NEWLINE: NEWLINE_CHAR -> skip;

// Switch to RESIDUE mode when see 'Residue conformations ---'
RESIDUE_START: 'Residue conformations' WS* [-]* NEWLINE_CHAR -> skip, pushMode(RESIDUE_MODE);

// ------------------------------------------------
// Residue mode - after 'Residue conformations ---'
// ------------------------------------------------
mode RESIDUE_MODE;
R_WS: WS_CHAR+ -> skip;
R_NEWLINE: NEWLINE_CHAR -> skip;
// Switch to Residue info mode when see ':'
R_COLUMN: COLUMN -> skip, popMode, pushMode(RESIDUE_INFO);

STRAND_POSITION: [A-Z] [1-9] [0-9]*;

// Switch to ADJACENT STACKINGS mode when see 'Adjacent stackings ---'
ADJ_STACKINGS_START: 'Adjacent stackings' R_WS* [-]* R_NEWLINE -> skip, popMode, pushMode(ADJ_STACKINGS_MODE);

// ---------------------------------------------------------
// Residue info mode - after ':'
// ---------------------------------------------------------
mode RESIDUE_INFO;
RI_WS: WS_CHAR+ -> skip;
RI_NEWLINE: NEWLINE_CHAR -> skip, popMode, pushMode(RESIDUE_MODE);

NUCLEOTIDE: IUPAC_CODE;
INFO: [a-zA-Z0-9_]+ -> skip;

// ---------------------------------------------------------
// Adjacent stackings mode - after 'Adjacent stackings ---'
// ---------------------------------------------------------
mode ADJ_STACKINGS_MODE;
AS_WS: WS_CHAR+ -> skip;
AS_NEWLINE: NEWLINE_CHAR -> skip;
AS_COLUMN: COLUMN -> skip;

AS_STACK: [A-Z] [1-9] [0-9]* '-' [A-Z] [1-9] [0-9]*;
AS_INFO: [a-zA-Z0-9_]+ -> skip;

// Switch to NON ADJACENT STACKING mode when see 'Non-Adjacent stackings ---'
NON_ADJ_STACKINGS_START: 'Non-Adjacent stackings' AS_WS* [-]* AS_NEWLINE -> skip, popMode, pushMode(NON_ADJ_STACKINGS_MODE);

// ---------------------------------------------------------
// Non adjacent stackings mode - after 'Non-Adjacent stackings ---'
// ---------------------------------------------------------
mode NON_ADJ_STACKINGS_MODE;
NAS_WS: WS_CHAR+ -> skip;
NAS_NEWLINE: NEWLINE_CHAR -> skip;
NAS_COLUMN: COLUMN -> skip;

NAS_STACK: [A-Z] [1-9] [0-9]* '-' [A-Z] [1-9] [0-9]*;
NAS_INFO: [a-zA-Z0-9_]+ -> skip;

INFO_SKIP: ('Number of stackings'
            | 'Number of adjacent stackings'
            | 'Number of non adjacent stackings') NAS_WS* '=' NAS_WS* [0-9]* -> skip;

// Switch to BASE_PAIRS mode when see 'Base-pairs ---'
BASE_PAIRS_START: 'Base-pairs' NAS_WS* [-]* NAS_NEWLINE -> skip, pushMode(BASE_PAIRS_MODE);

// ---------------------------------------------------------
// Base pairs mode - after 'Base-pairs ---'
// ---------------------------------------------------------
mode BASE_PAIRS_MODE;
B_WS: WS_CHAR+ -> skip;
B_NEWLINE: NEWLINE_CHAR -> skip;
B_COLUMN: COLUMN -> skip;
PAIRING: 'pairing' -> skip;
PAR: ('parallel' | 'antiparallel') -> skip;

POSITION_PAIR: [A-Z] [1-9] [0-9]* '-' [A-Z] [1-9] [0-9]*;
NUCLEOTIDE_PAIR: IUPAC_CODE '-' IUPAC_CODE;
BOND: [a-zA-Z0-9']+ '/' [a-zA-Z0-9']+;
ORIENTATION: 'cis' | 'trans';
B_INFO: [a-zA-Z0-9_]+ -> skip;