/**
 * ANTLR 4 parser grammar for 3DNA/X3DNA bp_order.dat output files.
 *
 * This grammar defines the structure of base-pair order files generated by 3DNA.
 * The format contains base-pair information with positions, base identities,
 * and various geometric parameters.
 *
 * @author Federico Di Petta
 * @see X3DNALexer
 */
parser grammar X3DNAParser;

options {
    tokenVocab = X3DNALexer;
}

// Root rule
x3dnaFile
    : line* EOF
    ;

line
    : basePairLine
    | contextLine
    | helixLine
    | numberLine
    ;

// Base pair line like:
//     1:     2    54 ....>A:...2_:[..G]G-*---U[..U]:..54_:A<....
basePairLine
    : lineNum=NUMBER COLON 
      pos1=NUMBER pos2=NUMBER 
      annotation1=ID? GT chainId1=CHAIN_ID COLON res1=residueInfo
      basePairSymbol=BASE_PAIR_SYMBOL
      res2=residueInfo COLON chainId2=CHAIN_ID LT annotation2=ID?
      parameters*
    ;

residueInfo
    : DOT* NUMBER UNDERSCORE? COLON? RESIDUE_NOTATION?
    | DOT* RESIDUE_NOTATION
    ;

parameters
    : NUMBER
    ;

// Context line like:
//    1:    0    2    3     3.48     6.83         ==>    -3.21    -6.46 * (    7.84*)
contextLine
    : NUMBER COLON NUMBER+ ARROW NUMBER+ STAR? LPAREN NUMBER STAR? RPAREN
    ;

// Helix line like:
//              1:  0  0  0  0  0 [1-2]
helixLine
    : NUMBER COLON NUMBER+ LBRACKET NUMBER DASH NUMBER RBRACKET
    ;

// Number line for end base-pair list
numberLine
    : NUMBER COLON NUMBER+
    ;
