/**
 * ANTLR 4 parser grammar for RNApolis output files.
 *
 * This grammar defines the structure of output files generated by RNApolis,
 * a suite of tools for RNA bioinformatics analysis. The output format consists
 * of one or more "strand" sections, each describing a single RNA strand or
 * molecule. The parser expects the input to be tokenized by the corresponding
 * lexer grammar (RNApolisLexer).
 *
 * @author Francesco Palozzi
 * @see RNApolisLexer
 */
parser grammar RNApolisParser;

options {
    tokenVocab = RNApolisLexer;
}

rnapolisFile:
    strandSection+ EOF
;

strandSection:
    strandName sequenceLine interactionLine*
;

strandName:
    TITLE
;

sequenceLine:
    NUCLEOTIDE
;

interactionLine:
    INTERACTION_TYPE interactionPattern
;

interactionPattern:
    SYMBOL+
;